# Generated by Django 5.1.7 on 2026-03-07 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_generatedtimetable_variant_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherUnavailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday')], max_length=3)),
                ('slot_index', models.IntegerField(help_text='0-7 corresponding to time slots')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailabilities', to='api.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'day', 'slot_index')},
            },
        ),
    ]
